#!/bin/sh
set -u
set -e

mkdir -p /usr/src/app
cp /tmp/scripts/launch/added/launch.sh /usr/src/app
cp /tmp/scripts/launch/added/sparkimage.sh /usr/src/app
cp /tmp/scripts/launch/added/server.js /usr/src/app