apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: oshinko-webui
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: o-webui
    name: o-webui
  spec:
    replicas: 1
    selector:
      app: o-webui
      deploymentconfig: o-webui
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: o-webui
          deploymentconfig: o-webui
      spec:
        containers:
        - env:
          - name: OPENSHIFT_OSHINKO_REST
            value: 172.84.0.1
          - name: OPENSHIFT_OSHINKO_REST_PORT
            value: "45564"
          image: 172.30.122.181:5000/oshinko-demo/o-webui@sha256:6bde2e922262f07f999bfd9ddded5d88d98e41dd6d5e125f6ca2c040509549f1
          imagePullPolicy: Always
          name: o-webui
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - o-webui
        from:
          kind: ImageStreamTag
          name: o-webui:latest
          namespace: oshinko-demo
      type: ImageChange
  status: {}
